export const MINING = [
  "Lv.1 Upgrading Metal",
  "Lv.1 Muspellium",
  "Lv.1 Rough Oridecon",
  "Lv.1 Rough Elunium",
  "Lv.1 Rough Bradium",
  "Lv.1 Coal Ore",
  "Lv.1 Pure Jewelstone",
  "Lv.1 Impure Jewelstone",
  "Lv.1 Iron Ore",
  "Lv.1 Silver Ore",
  "Lv.1 Gold Ore",
  "Lv.2 Upgrading Metal",
  "Lv.2 Muspellium",
  "Lv.2 Rough Oridecon",
  "Lv.2 Rough Elunium",
  "Lv.2 Rough Bradium",
  "Lv.1 Blessed Ore",
  "Lv.1 Protected Ore",
  "Lv.3 Upgrading Metal",
  "Lv.3 Muspellium",
  "Lv.2 Pure Jewelstone",
  "Lv.2 Impure Jewelstone",
  "Lv.2 Iron Ore",
  "Lv.2 Silver Ore",
  "Lv.2 Gold Ore",
  "Lv.4 Muspellium",
  "Lv.3 Rough Oridecon",
  "Lv.3 Rough Elunium",
  "Lv.3 Rough Bradium",
  "Lv.2 Blessed Ore",
  "Lv.2 Protected Ore",
  "Lv.4 Upgrading Metal",
] as const;

export const GATHERING = [
  "Shattering Shroom",
  "Tough Vine",
  "Arcane Flower",
  "Goldflower",
  "Scorched Mushroom",
  "Withered Chastetree",
  "Rot Root Grass",
  "Guiding Grass",
  "Stoneheart Shroom",
  "Stol-nut",
  "Nitraria Seed",
  "Desert Welwitschia",
  "Water Seeking Flower",
  "Sea Gem Grass",
  "Firefly Grass",
  "Aquatic Reed",
  "Winter Cherry",
  "Singin Plant",
  "Grim Grass",
  "Ochre Seedling",
  "Quiet Flower",
  "Cliff Moss",
  "Glowing Mushroom",
  "Phantom Vine",
  "Moonflower",
  "Praying Flower",
  "Crystal Rose",
] as const;

export const FISHING = [
  "Turquoise",
  "Cobblestone",
  "Shell",
  "Conch Snail",
  "White Cloud Fish",
  "Pure-water Sturgeon",
  "Vulcanfish",
  "Hardshell Crab",
  "Emberfish",
  "Starlight Snail",
  "Glowfish",
  "Night Pearl",
  "Yarn Marina",
  "Sandfish",
  "Maple Fish",
  "Butterfly Cowrie",
  "Whitefeather Cowrie",
  "Mystic Mussel",
  "Tube-eye",
  "Soldierfish",
  "Rainbow Coral",
  "Ghostfish",
  "Devilfish",
  "Clearwater Pearl",
  "Dusk Fish",
  "Armored Crab",
  "Pupa Sulcata",
  "Swordfish",
  "Hunter Fish",
  "Crystal Acanthodean",
] as const;

export const CRAFTING = [
  "STR Stone I",
  "AGI Stone I",
  "INT Stone I",
  "VIT Stone I",
  "LUK Stone I",
  "DEX Stone I",
  "Iron I",
  "Silver I",
  "Gold I",
  "STR Stone II",
  "AGI Stone II",
  "INT Stone II",
  "VIT Stone II",
  "LUK Stone II",
  "DEX Stone II",
  "Iron II",
  "Silver II",
  "Gold II",
] as const;

export const EQUIPMENT_CULTIVATION = [
  "Phracon I",
  "Carnium I",
  "Bascyx I",
  "Sharpening Enchantment Stone",
  "Toughening Enchantment Stone",
  "Secret Enchantment Stone",
  "Oridecon",
  "Elenium",
  "Bradium",
  "Phracon II",
  "Carnium II",
  "Bascyx II",
  "Blazing Enchantment Stone",
  "Hardening Enchantment Stone",
  "Gold Enchantment Stone",
  "Enriched Oridecon",
  "Enriched Elenium",
  "Enriched Bradium",
  "Blessed Oridecon I",
  "Blessed Elunium I",
  "Blessed Bradium I",
  "Weapon Protection Stone I",
  "Armor Protection Stone I",
  "Accessory Protection Stone I",
  "Phracon III",
  "Carnium III",
  "Bascyx III",
  "Tidal Enchantment Stone",
  "Crystallize Enchantment Stone",
  "Glowing Star Enchantment Stone",
  "Gloomy Enchantment Stone",
  "Petrifying Enchantment Stone",
  "Silverspirit Star Enchantment Stone",
  "HD Oridecon",
  "HD Elenium",
  "HD Bradium",
  "Blessed Oridecon II",
  "Blessed Elunium II",
  "Blessed Bradium II",
  "Weapon Protection Stone II",
  "Armor Protection Stone II",
  "Accessory Protection Stone II",
  "Phracon IV",
  "Carnium IV",
  "Bascyx IV",
  "Cold Enchantment Stone",
  "Praying Enchantment Stone",
  "Rosecrystal Enchantment Stone",
] as const;
